package mantle.product.price;
dialect "mvel"
import org.moqui.util.ContextStack
import java.math.BigDecimal
global org.moqui.context.ExecutionContext ec

rule "Demo Product One-Two 10% Off"
when
    $context : ContextStack(productId == "1") from ec.context
then

    System.out.println("========$context.get(\"price\")=====" + $context.get("price"));

    $context.put("price", new BigDecimal(0.9));
end
